#!/usr/bin/python3
# This is an HTTP Fuzzer

import socket
import sys
import time

size = 100

while size < 3000:
    try:
        input = "A" * size

        # Replace with appropriate form data
        inputbuffer = "username=" + input + "&password=A"

        print("Sending buffer with {0} bytes".format(size))
        # http headers

        buffer = "POST /login HTTP/1.1\r\n"
        buffer += "Host: 127.0.0.1\r\n"
        buffer += "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0\r\n"
        buffer += "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\n"
        buffer += "Accept-Language: en-US,en;q=0.5\r\n"
        buffer += "Accept-Encoding: gzip, deflate\r\n"
        buffer += "Content-Type: application/x-www-form-urlencoded\r\n"
        buffer += "Content-Length: " + str(len(inputbuffer)) + "\r\n"
        buffer += "Connection: keep-alive\r\n"
        buffer += "Referer: http://192.168.149.10/login\r\n"
        buffer += "\r\n"

        buffer += inputbuffer

        buffer = bytes(buffer, 'utf-8')

        s = socket.socket()
        s.connect(("192.168.149.10", 80))

        s.send(buffer)
        s.close()

        size += 100
        time.sleep(1)
    

    except:
        print("Can't Connect")
        sys.exit()

print("\nDone!")
